In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('D:\College\REG EX\Dataset\Data.csv')

In [3]:
df.head(11)

Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Germany  40.0      NaN       Yes
5    France  35.0  58000.0       Yes
6     Spain   NaN  52000.0        No
7    France  48.0  79000.0       Yes
8   Germany  50.0  83000.0        No
9    France  37.0  67000.0       Yes
10   France  37.0  67000.0       Yes

In [4]:
df.duplicated().sum()  # if sum is not 0 means there is a duplicate

1

In [5]:
df.drop_duplicates(inplace=True)

In [6]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [8]:
df.fillna(0)  # replaces NA with 

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      0.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   0.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [9]:
df.dropna()  # drops rows with na 0

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [10]:
avg_age = df['Age'].mean()
avg_salary = df['Salary'].mean()
print(avg_age)
print(avg_salary)

38.77777777777778
63777.77777777778


In [11]:
df['Age'].replace(np.nan , avg_age , inplace=True)
df['Salary'].replace(np.nan , avg_salary , inplace=True)
df

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

## Using Scikit learn 

In [12]:
df2 = pd.read_csv('D:\College\REG EX\Dataset\Data.csv')
df2.drop_duplicates(inplace = True)
X = df2.iloc[:,:-1].values
Y = df2.iloc[:,-1].values

In [13]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
from sklearn.impute import SimpleImputer  
# SimpleImpumter : helpful in handling the missing data in the predictive model dataset.
#                  It replaces the NaN values with a specified placeholder. 

imp = SimpleImputer(missing_values=np.nan , strategy='mean')  
# Imputer object using the mean strategy and 
# missing_values type for imputation

imp.fit(X[:,1:3])  # Fitting the data to the imputer object
X[:,1:3] = imp.fit_transform(X[:,1:3])  # Fit to data, then transform it.
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()  # Standardize features by removing the mean and scaling to unit variance
X[:, 1:3] = sc.fit_transform(X[:, 1:3])
X

array([['France', 0.758874361590019, 0.7494732544921677],
       ['Spain', -1.7115038793306814, -1.4381784072687531],
       ['Germany', -1.2755547779917342, -0.8912654918285229],
       ['Spain', -0.1130238410878753, -0.253200423814921],
       ['Germany', 0.17760889313808945, 6.632191985654332e-16],
       ['France', -0.5489729424268225, -0.5266568815350361],
       ['Spain', 0.0, -1.0735697969752662],
       ['France', 1.3401398300419485, 1.3875383225057696],
       ['Germany', 1.6307725642679132, 1.7521469327992565],
       ['France', -0.2583402082008577, 0.29371249162530916]], dtype=object)

In [16]:
X[:,1].var()

1.0

In [17]:
X[:,2].var()

1.0000000000000002

In [18]:
dummy1 = pd.get_dummies(df['Country']) # get_dummies : Convert categorical variable into dummy/indicator variables.
dummy1

France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
4       0        1      0
5       1        0      0
6       0        0      1
7       1        0      0
8       0        1      0
9       1        0      0

In [19]:
df = pd.concat([dummy1,df] , axis=1)
df

France  Germany  Spain  Country        Age        Salary Purchased
0       1        0      0   France  44.000000  72000.000000        No
1       0        0      1    Spain  27.000000  48000.000000       Yes
2       0        1      0  Germany  30.000000  54000.000000        No
3       0        0      1    Spain  38.000000  61000.000000        No
4       0        1      0  Germany  40.000000  63777.777778       Yes
5       1        0      0   France  35.000000  58000.000000       Yes
6       0        0      1    Spain  38.777778  52000.000000        No
7       1        0      0   France  48.000000  79000.000000       Yes
8       0        1      0  Germany  50.000000  83000.000000        No
9       1        0      0   France  37.000000  67000.000000       Yes

In [20]:
dummy2 = pd.get_dummies(df['Purchased'])
dummy2

No  Yes
0   1    0
1   0    1
2   1    0
3   1    0
4   0    1
5   0    1
6   1    0
7   0    1
8   1    0
9   0    1

In [21]:
X

array([['France', 0.758874361590019, 0.7494732544921677],
       ['Spain', -1.7115038793306814, -1.4381784072687531],
       ['Germany', -1.2755547779917342, -0.8912654918285229],
       ['Spain', -0.1130238410878753, -0.253200423814921],
       ['Germany', 0.17760889313808945, 6.632191985654332e-16],
       ['France', -0.5489729424268225, -0.5266568815350361],
       ['Spain', 0.0, -1.0735697969752662],
       ['France', 1.3401398300419485, 1.3875383225057696],
       ['Germany', 1.6307725642679132, 1.7521469327992565],
       ['France', -0.2583402082008577, 0.29371249162530916]], dtype=object)

## ColumnTransformer
ColumnTransformer takes in a list, which contains tuples of the transformations we wish to perform on the different columns. Each tuple expects 3 comma-separated values: first, the name of the transformer, which can be practically anything (passed as a string), second is the estimator object, and the final one being the columns upon which we wish to perform that operation.

## OneHotEncoder

In this technique, we each of the categorical parameters, it will prepare separate columns for both Male and Female label. SO, whenever there is Male in Gender, it will 1 in Male column and 0 in Female column and vice-versa.

Note: OneHotEncoder can’t handle missing values, hence it is important to get rid of them before encoding.

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder = 'passthrough')

# By specifying remainder='passthrough', all remaining columns that were not specified in transformers will 
# be automatically passed through. This subset of columns is concatenated with the output of the transformers. 
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921],
       [0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361],
       [0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565],
       [1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916]],
      dtype=object)

In [23]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## LabelEncoder

LabelEncoder can be used to normalize labels.It can also be used to transform non-numerical labels (as long as they are hashable and comparable) to numerical labels.

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [25]:
z = df['Country'].values
z = le.fit_transform(z)
z

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [26]:
print(X)
print(Y)

[[1.0 0.0 0.0 0.758874361590019 0.7494732544921677]
 [0.0 0.0 1.0 -1.7115038793306814 -1.4381784072687531]
 [0.0 1.0 0.0 -1.2755547779917342 -0.8912654918285229]
 [0.0 0.0 1.0 -0.1130238410878753 -0.253200423814921]
 [0.0 1.0 0.0 0.17760889313808945 6.632191985654332e-16]
 [1.0 0.0 0.0 -0.5489729424268225 -0.5266568815350361]
 [0.0 0.0 1.0 0.0 -1.0735697969752662]
 [1.0 0.0 0.0 1.3401398300419485 1.3875383225057696]
 [0.0 1.0 0.0 1.6307725642679132 1.7521469327992565]
 [1.0 0.0 0.0 -0.2583402082008577 0.29371249162530916]]
[0 1 0 0 1 1 0 1 0 1]


In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [28]:
x_train

array([[0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16],
       [1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696],
       [0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921],
       [1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361]],
      dtype=object)

In [29]:
x_test

array([[0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565]],
      dtype=object)

In [30]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [31]:
y_test

array([0, 0])