# Numpy

In [2]:
import numpy as np

In [2]:
a = np.arange(100000)    # Return evenly spaced values within a given interval.
l = list(range(100000))

In [3]:
%timeit for i in range(5000): a1 = a * 2

338 ms ± 12.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit for i in range(5000): l1 = l * 2

7.72 s ± 2.48 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
a = np.arange(5)
a * 2

array([0, 2, 4, 6, 8])

In [14]:
a1 = np.arange(5)   # default initial is 0
a1

array([5, 6, 7, 8, 9])

In [15]:
b1 = np.arange(5,10)   # here initial is 5 and end is 10
b1

array([5, 6, 7, 8, 9])

In [5]:
l = [1, 2, 3, 4]
l * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [8]:
data = [[1, 2, 3, 4], [5, 6, 7,8]]
a1 = np.array(data)
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
type(a1)

numpy.ndarray

In [10]:
a1.shape

(2, 4)

In [11]:
a1.dtype

dtype('int32')

In [12]:
a1.ndim

2

In [13]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a1 = a1.astype('float64')

In [15]:
type(a1)

numpy.ndarray

In [16]:
a1.dtype

dtype('float64')

In [17]:
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
a1 = np.zeros((3, 3, 3))   # (row , column , rank)

In [20]:
a1

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
a1.ndim

3

In [22]:
a1.shape

(3, 3, 3)

In [23]:
np.eye(4)  # 4 will be the dimentions i.e., in this case 4*4 matrix
           # Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.full((3, 3), fill_value = 6)  # Return a new array of given shape and type, filled with fill_value.

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [25]:
np.empty((3, 3))   # gives random values available in buffer. (saves time for initialization)
                   # Return a new array of given shape and type, without initializing entries.

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## Arithmatic Operations

In [26]:
a1 = np.array([1, 2, 3, 4, 5, 6])
a1

array([1, 2, 3, 4, 5, 6])

In [27]:
a1 + 2

array([3, 4, 5, 6, 7, 8])

In [28]:
a1 + a1

array([ 2,  4,  6,  8, 10, 12])

In [29]:
a1 * 5

array([ 5, 10, 15, 20, 25, 30])

In [30]:
a1 // 2    # floar division

array([0, 1, 1, 2, 2, 3], dtype=int32)

In [31]:
6 // a1

array([6, 3, 2, 1, 1, 1], dtype=int32)

In [32]:
a1 ** 2

array([ 1,  4,  9, 16, 25, 36], dtype=int32)

In [33]:
a1 ** a1

array([    1,     4,    27,   256,  3125, 46656], dtype=int32)

In [34]:
a1 * a1

array([ 1,  4,  9, 16, 25, 36])

In [35]:
a1 = np.array([1, 2, 3, 4, 5, 6])
a2 = np.array([7, 8, 9, 10, 11, 12])

In [36]:
a1 < a2

array([ True,  True,  True,  True,  True,  True])

In [37]:
a1 > a2

array([False, False, False, False, False, False])

## Indexing and slicing

In [38]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a[-1]

9

In [40]:
a[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [41]:
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a2 = np.arange(11)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
a2[:3] = 11
a2

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
a2[:] = 3
a2

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [11]:
a1 = np.array(10)
c1 = a1.copy()
c1

array(10)

In [17]:
print(c1*2)

20


In [18]:
a1 = np.array([1,2,3,4,5])
c1 = a1.copy()
c1

array([1, 2, 3, 4, 5])

In [46]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
a.shape

(16,)

In [48]:
a1 = a.reshape((16, 1))

In [49]:
a1.shape

(16, 1)

In [50]:
a1.ndim  # number of dimensions : (like 2 for rows & columns)

2

In [51]:
b = a.reshape((4, 4))   # total elements must be same
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
np.transpose(b)

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [53]:
np.dot(b, b.T)   # returns dot product of both arrays

array([[ 14,  38,  62,  86],
       [ 38, 126, 214, 302],
       [ 62, 214, 366, 518],
       [ 86, 302, 518, 734]])

In [54]:
a = np.array([1, 5, 6, 5 ,2])
a

array([1, 5, 6, 5, 2])

In [55]:
np.square(a)

array([ 1, 25, 36, 25,  4], dtype=int32)

In [56]:
np.sort(a)

array([1, 2, 5, 5, 6])

In [57]:
np.abs([-1, -5, -3, -9])   # returns absolute value

array([1, 5, 3, 9])

In [58]:
a1 = np.array([2, 5, 4, 1, 6, 5, 9])
a2 = np.array([7, 8, 9, 5, 3, 1, 0])
np.maximum(a1, a2)                   # compares each element of both arrays and gives the max element as op

array([7, 8, 9, 5, 6, 5, 9])

In [59]:
np.minimum(a1, a2)     # compares each element of both arrays and gives the min element as op

array([2, 5, 4, 1, 3, 1, 0])

In [60]:
np.power(a1, a2)

array([   128, 390625, 262144,      1,    216,      5,      1],
      dtype=int32)

In [61]:
a1 ** a2

array([   128, 390625, 262144,      1,    216,      5,      1],
      dtype=int32)

In [62]:
np.greater(a1, a2)

array([False, False, False, False,  True,  True,  True])

In [63]:
np.less(a1, a2)

array([ True,  True,  True,  True, False, False, False])

In [64]:
np.cbrt([8, 27])   # Return the cube-root of an array, element-wise.

array([2., 3.])

In [65]:
a.sum()

19

In [66]:
a.max()

6

In [67]:
a.std()  # std deviation

1.9390719429665317

In [68]:
a.var()  # varience

3.7600000000000002

In [69]:
a.cumsum()   # Return the cumulative sum of the elements along a given axis.

array([ 1,  6, 12, 17, 19], dtype=int32)

In [19]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

axis = 0 is along Y axis
axis = 1 is along X axis

In [20]:
np.cumsum(a,axis=0)      # sum over rows for each of the 3 columns

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [21]:
np.cumsum(a,axis=1)      # sum over columns for each of the 2 rows

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [70]:
a = np.arange(25)

In [71]:
a = a.reshape((5, 5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
a.mean(axis = 1) # axis 1 = along row, axis 0 = along column

array([ 2.,  7., 12., 17., 22.])

In [73]:
a.mean(axis = 0)

array([10., 11., 12., 13., 14.])

In [74]:
a.var(axis = 0)

array([50., 50., 50., 50., 50.])

In [75]:
a.dot(a.T)

array([[  30,   80,  130,  180,  230],
       [  80,  255,  430,  605,  780],
       [ 130,  430,  730, 1030, 1330],
       [ 180,  605, 1030, 1455, 1880],
       [ 230,  780, 1330, 1880, 2430]])

## Linear Algebra 

In [76]:
from numpy.linalg import det, inv, eig   #numpy.linalg : linear algebra

In [77]:
a = np.array([1, 4, 6, 5, 8, 7, 9, 3, 2]).reshape(3, 3)
a

array([[1, 4, 6],
       [5, 8, 7],
       [9, 3, 2]])

In [78]:
inv(a)   # Compute the (multiplicative) inverse of a matrix.

array([[ 0.03703704, -0.07407407,  0.14814815],
       [-0.39259259,  0.38518519, -0.17037037],
       [ 0.42222222, -0.24444444,  0.08888889]])

In [79]:
eig(a)   # Compute the eigenvalues and right eigenvectors of a square array.

(array([15.        , -5.60555128,  1.60555128]),
 array([[-0.42313262, -0.59880267,  0.24104363],
        [-0.77372822, -0.18130286, -0.79611302],
        [-0.47149064,  0.78010553,  0.55506939]]))

In [80]:
a

array([[1, 4, 6],
       [5, 8, 7],
       [9, 3, 2]])

In [86]:
np.concatenate((a, a.T), axis = 1)

array([[1, 4, 6, 1, 5, 9],
       [5, 8, 7, 4, 8, 3],
       [9, 3, 2, 6, 7, 2]])

In [85]:
a.T

array([[1, 5, 9],
       [4, 8, 3],
       [6, 7, 2]])